CREATE SCHEMA IF NOT EXISTS BBDD;
USE BBDD;

CREATE TABLE Libro (
    ID INT PRIMARY KEY
);

CREATE TABLE FichaBibliografica (
    ID INT PRIMARY KEY,
    Id_libro INT NOT NULL UNIQUE,
    Titulo VARCHAR(200),
    Autor VARCHAR(200),
    Anio SMALLINT NOT NULL – CHECK (Anio BETWEEN 1450 AND 2025),
    Editorial VARCHAR(200),
    FOREIGN KEY (Id_libro) REFERENCES Libro(ID)
);
